# Generated by Django 4.2.4 on 2023-08-30 18:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='mahsulot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.TextField(max_length=25)),
                ('ics', models.DateField(default=datetime.datetime.now)),
            ],
            options={
                'db_table': 'mahsulot',
            },
        ),
        migrations.CreateModel(
            name='sotuvchi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.TextField(max_length=25)),
                ('familiya', models.TextField(max_length=25)),
                ('tugilgan_sana', models.DateField()),
            ],
            options={
                'db_table': 'sotuvchi',
            },
        ),
    ]
