# Generated by Django 4.2.4 on 2023-08-31 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bozor', '0002_mahsulot_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mahsulot',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bozor.sotuvchi'),
        ),
    ]
