# Generated by Django 4.2.4 on 2023-08-31 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bozor', '0003_alter_mahsulot_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='mahsulot',
            name='miqdori',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
